name: RELEASE

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm dist

    - name: Upload XPI to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: keybrpp.xpi
        asset_name: keybrpp.xpi
        tag: ${{ github.event.release.tag_name }}

    - name: Upload update.json to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: update.json
        asset_name: update.json
        tag: ${{ github.event.release.tag_name }}